apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  encryptionKey: {{ .Values.secrets.encryptionKey | quote }}
  anthropicApiKey: {{ .Values.secrets.anthropicApiKey | quote }}
